version: '3.4'

services:
  # Database service
  npaperless-db:
    container_name: npaperless-db
    image: postgres:latest
    environment:
      POSTGRES_DB: npaperless
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - npaperless-network
    restart: unless-stopped

  #MinIO Storage
  npaperless-storage:
    container_name: npaperless-storage
    image: quay.io/minio/minio
    environment:
      - MINIO_ROOT_USER=npaperless
      - MINIO_ROOT_PASSWORD=npaperless
      - MINIO_ACCESS_KEY=npaperless
      - MINIO_SECRET_KEY=npaperless
      - MINIO_DEFAULT_BUCKETS=npaperless-docs
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - minio-data:/data
    command: ["server", "/data", "--console-address", ":9090"]

  # REST service
  npaperless-rest:
    container_name: npaperless-rest
    build:
      context: .
      dockerfile:  NPaperless.REST/Dockerfile
    ports:
      - 8081:8081
    networks:
      - npaperless-network
    restart: unless-stopped
    depends_on:
      - npaperless-db

  # WebUI service
  npaperless-webui:
    container_name: npaperless-webui
    image: nginx:latest
    volumes:
      - ./NPaperLess.WebUI:/usr/share/nginx/html/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - npaperless-network
    restart: unless-stopped
    depends_on:
      - npaperless-rest

networks:
  npaperless-network:
    driver: bridge

volumes:
  db-data:
  minio-data: