version: '3.4'

services:
  npaperless-services:
    container_name: npaperless-services
    image: ${DOCKER_REGISTRY-}npaperlessservices
    build:
      context: .
      dockerfile:  NPaperless.Services/Dockerfile
    ports:
      - 8081:8081
    networks:
      - npaperless-network
    restart: unless-stopped
  npaperless-webui:
    container_name: npaperless-webui
    image: nginx:latest
    volumes:
      - ./PaperLess.WebUI:/usr/share/nginx/html/
      - ./Paperless.WebUI/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - npaperless-network
    restart: unless-stopped

networks:
  npaperless-network:
    driver: bridge